---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "{{db.host}}"
  name: "{{db.host}}"
  namespace: "{{namespace}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{db.host}}"
  template:
    metadata:
      labels:
        app: "{{db.host}}"
    spec:
      containers:
      - name: "mongodb"
        imagePullPolicy: Always
        image: "registry.redhat.io/rhscl/mongodb-36-rhel7:latest"
        env:
        - name: MONGODB_USER
          value: "{{db.host}}"
        - name: MONGODB_PASSWORD
          value: "{{db.host}}"
        - name: MONGODB_ADMIN_PASSWORD
          value: "{{db.host}}"
        - name: MONGODB_DATABASE
          value: "{{db.name}}"
        ports:
          - containerPort: 27017
---
kind: Service
apiVersion: v1
metadata:
  name: "{{db.host}}"
  namespace: "{{namespace}}"
spec:
  selector:
    app: "{{db.host}}"
  ports:
  - name: mongo
    port: 27017
